# Generated by Django 5.0.1 on 2024-02-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='qr_data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
